default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: freshcart_backend_development

test:
  <<: *default
  database: freshcart_backend_test

production:
  <<: *default
  database: freshcart_backend_production
